name          'cesnet-pig'
version       '0.1.0'
source        'http://scientific.zcu.cz/git/cesnet-pig.git'
author        'František Dvořák <valtri@civ.zcu.cz>'
license       'ASL 2.0'
summary       'Pig Setup'
description   'Pig Setup'
project_page  'scientific.zcu.cz'

dependency 'puppetlabs/stdlib'
